# Generated by Django 3.2.5 on 2021-12-08 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=20, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('group_folks', models.ManyToManyField(related_name='group_folks', to=settings.AUTH_USER_MODEL)),
                ('group_founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_founder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
