# Generated by Django 3.2.5 on 2021-12-06 13:44

import community.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, default=community.models.default_profile_picture_upload_location, max_length=255, null=True, upload_to=community.models.profile_picture_upload_location)),
                ('cover_image', models.ImageField(blank=True, default=community.models.default_cover_picture_upload_location, max_length=255, null=True, upload_to=community.models.profile_cover_upload_location)),
                ('privacy', models.CharField(choices=[('1', 'Private'), ('2', 'Public')], default='2', max_length=5)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
