# Generated by Django 3.2.5 on 2021-12-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='address',
            field=models.CharField(blank=True, max_length=30, verbose_name='Address'),
        ),
    ]
