# Generated by Django 3.2.5 on 2021-12-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='f_name',
            field=models.CharField(blank=True, default='First Name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='l_name',
            field=models.CharField(blank=True, default='Last Name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='privacy',
            field=models.CharField(blank=True, choices=[('1', 'Private'), ('2', 'Public')], default='1', max_length=5, null=True),
        ),
    ]
