# Generated by Django 3.2.5 on 2021-12-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211208_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='f_name',
            field=models.CharField(default='First Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='l_name',
            field=models.CharField(default='Last Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='privacy',
            field=models.CharField(choices=[('1', 'Private'), ('2', 'Public')], default='1', max_length=5),
        ),
    ]
