# Generated by Django 3.2.5 on 2021-12-08 12:15

from django.db import migrations, models
import story.models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20211208_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_picture',
        ),
        migrations.AddField(
            model_name='communitystory',
            name='story_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=story.models.community_story_picture_upload_location),
        ),
        migrations.AddField(
            model_name='groupstory',
            name='story_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=story.models.group_story_picture_upload_location),
        ),
        migrations.AddField(
            model_name='userstory',
            name='story_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=story.models.user_story_picture_upload_location),
        ),
    ]
